<?php

use App\Event;
use Illuminate\Database\Seeder;

class EventsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Event::truncate();
        Event::create(array('id' => 1, 'category_id' => 1, 'name' => 'TOM ODELL Jubilee Road Tour', 'description' => 'The author of the super hit “Another Love”, winner of the prestigious Brit Award and one of today\'s most popular youngsinger - songwriters Tom Odell will return to Latvia on January 29, 2019 as a part of his latest tour “Jubilee Road Tour”.', 'start_time' => '2019/5/29  20:00:00', 'location' => 'Palladium Rīga', 'rating' => 5));
        Event::create(array('id' => 2, 'category_id' => 1, 'name' => 'Ewert and The Two Dragons - Hands Around the Moon Tour', 'description' => 'Ewert and The Two Dragons are coming back to Riga to present their new record „Hands Around the Moon“ out November 23rd! The new record is milestone for the band on their already ten year journey during which they have endlessly toured around Europe and North-America. „Hands Around the Moon“ is full of fresh ideas and new approaches, which were all brought to life together with producer Sander Mölder. ', 'start_time' => '2019/4/9  21:00:00', 'location' => 'Palladium Rīga', 'rating' => 7));
        Event::create(array('id' => 3, 'category_id' => 1, 'name' => 'BEL SUONO Piano magic show', 'description' => 'Three grand pianos, three young virtuoso pianists and their six flying hands will create a brilliant mix of classical, pop, rock and world soundtracks! Bel Suono - unique representatives of the piano crossover genre in Russia, as well as graduates of the most prestigious musical university of their homeland. They managed to win public recognition in many countries of the world: Israel, Monaco, Austria, Bulgaria, Switzerland ... Last summer, the trio performed successfully in the largest halls of Jurmala and Liepaja. On February 13 as part of of the European tour of St. Valentine\'s Day, the show of three pianos will present a program that will include Vivaldi and the Queen, Glinka and Brahms, Liszt and Maroon 5, Beethoven and Strauss, the Games of Thrones and other great works, which will be featured in the original Bel Suono author’s treatment! Do not miss this bright musical event in your city!', 'start_time' => '2019/4/13  19:30:00', 'location' => 'Rīgas Kongresu nams', 'rating' => 9));
        Event::create(array('id' => 4, 'category_id' => 1, 'name' => 'MAROKUBA. Marialy Pacheco & Rhani Krija', 'description' => 'The stations in the career of cuban pianist Marialy Pacheco are impressive: her debut album wasproduced by Roberto Fonseca, pianist of the legendary Ibrahim Ferrer (Buena Vista Social Club) and in 2012 she became the first woman to ever win the Montreux Jazzfestival Solo Piano Competition. Rightly so! For although her admiration for Ruben Gonzales, Oscar Peterson and Keith Jarrett is palpable in her sound, Marialy Pacheco magically creates something of her own and genuinely unique on the piano.', 'start_time' => '2019/4/16  19:00:00', 'location' => 'Spīķeru koncertzāle', 'rating' => 7));
        Event::create(array('id' => 5, 'category_id' => 1, 'name' => 'ÓLAFUR ARNALDS - re:member 2019', 'description' => 'BAFTA winning artist, composer, musician and producer Ólafur Arnalds has expanded his current worldwide tour, his first in over three years. After a sold out European run this spring that included the prestigious Royal Albert Hall in London, Ólafur announced a new album, re:member, that was released on August 24 via Mercury KX. The first two singles from the album, title track re:member and unfold, have excited and delighted fans across the globe. And now Ólafur and his team of fellow craftsmen and musicians are back on the road with an all-new live show.', 'start_time' => '2019/4/18  19:00:00', 'location' => 'Alexela Kontserdimaja, Tallinn', 'rating' => 9));
        Event::create(array('id' => 6, 'category_id' => 1, 'name' => 'PLACIDO DOMINGO & Estonian National Symphony Orchestra', 'description' => 'Plácido Domingo‘s show normally includes operatic arias & duets, since he is known as an opera singer first and foremost, followed by highlights from Viennese Operettas, Broadway Classics and Zarzuela jewels; Zarzuela being the Spanish repertoire which his parents used to sing. It is a very versatile program filled with highlights of most of the genres that he has sang throughout his career. And he will close the concert with some of his signature fire work numbers.', 'start_time' => '2019/4/19  20:00:00', 'location' => 'Saku Suurhall', 'rating' => 6));
        Event::create(array('id' => 7, 'category_id' => 1, 'name' => 'Laima Vaikule & Freedom Ballet', 'description' => 'After a six-year pause, Laima Vaikule is preparing a special solo concert that will take place on March 30 in Arena Riga. Laima admits: “Every performance in Latvia is important for me, but such a huge solo concert as planned for the next spring is a rare and special event.”', 'start_time' => '2019/4/30  19:00:00', 'location' => 'Arēna Rīga', 'rating' => 7));
        Event::create(array('id' => 8, 'category_id' => 1, 'name' => 'DAGAMBA feat TCHAIKOVSKY', 'description' => 'The band DAGAMBA - the hooligans of classical music realise a new video for the song “Nutcracker Rock” from the new “DAGAMBA feat TCHAIKOVSKY” concert program and announce an extraordinary show that will take place next year, April 12 in Arena Riga. Only in shopping centre “Spice” tickets will be available for a special price until September 2.', 'start_time' => '2019/5/12  20:00:00', 'location' => 'Arēna Rīga', 'rating' => 10));
        Event::create(array('id' => 9, 'category_id' => 2, 'name' => 'Mary Poppins', 'description' => 'Disney and Cameron Mackintosh\'s multi award-winning musical Mary Poppins is returning to its original West End home at the Prince Edward Theatre from 23 October 2019. The magical story of the world\'s favourite nanny is triumphantly and spectacularly brought to the stage with dazzling choreography, incredible effects and unforgettable songs. It will star Zizi Strallen, returning to play the title role following great acclaim on the recent sell-out international tour, and Charlie Stemp as Bert, who recently gave an award-winning performance as Arthur Kipps in Cameron Mackintosh\'s production of Half A Sixpence.', 'start_time' => '2019/4/12  12:00:00', 'location' => 'Prince Edward Theatre', 'rating' => 7));
        Event::create(array('id' => 10, 'category_id' => 2, 'name' => 'The Phantom of the Opera', 'description' => 'Seen by over 100 million people worldwide, Cameron Mackintosh\'s The Phantom of the Opera is the highest grossing musical of all time. Now in its 30th record-breaking year, this multi-award winning musical continues to captivate audiences at Her Majesty\'s Theatre in London\'s West End. Far beneath the majesty and splendour of the Paris Opera House, hides the Phantom in a shadowy existence. Shamed by his physical appearance and feared by all, the love he holds for his beautiful protegee Christine Daae is so strong that even her heart cannot resist. Andrew Lloyd Webber\'s mesmerising score magically combines with jaw-dropping scenery and breath-taking special effects to bring this tragic love story to life each night.', 'start_time' => '2019/4/19  18:00:00', 'location' => 'Her Majesty\'s Theatre', 'rating' => 10));
        Event::create(array('id' => 11, 'category_id' => 2, 'name' => 'Wicked', 'description' => 'WICKED, the West End and Broadway musical sensation, is the recipient of more than 100 major international awards, including three Tony Awards on Broadway and two Olivier Audience Awards in London.  Already the 5th longest running musical currently playing in the West End and now seen by more than 9 million people in London alone, WICKED remains “one of the most popular West End musicals ever” (Evening Standard).', 'start_time' => '2019/4/30  18:30:00', 'location' => 'Apollo Victoria', 'rating' => 9));
        Event::create(array('id' => 12, 'category_id' => 2, 'name' => 'Don Quixote', 'description' => 'After a lifetime of reading books on chivalry, one eccentric old man heads off on a rumbustious quest to become a wandering knight accompanied by his faithful and equally ill-suited servant, ‘riotously performed by David Threlfall as Don Quixote and Rufus Hound as Sancho Panza’ (The Times). Taking up a lance and sword, Don Quixote sets out on a hilarious journey across medieval Spain, defending the helpless and vanquishing the wicked. Hopelessly unprepared and increasingly losing his grip on reality, with each calamitous adventure the two hapless heroes experience, the romantic ideal of Quixote’s books seems further away than ever.', 'start_time' => '2019/4/20  16:00:00', 'location' => 'Garrick Theatre', 'rating' => 10));
        Event::create(array('id' => 13, 'category_id' => 2, 'name' => 'La Traviata', 'description' => 'Joyce El-Khoury, Ekaterina Bakanova and Corinne Winters lead three excellent casts in Richard Eyre’s much-loved production of Verdi’s most famous opera.', 'start_time' => '2019/4/17  17:00:00', 'location' => 'Royal Opera House', 'rating' => 6));
        Event::create(array('id' => 14, 'category_id' => 2, 'name' => 'Kieran Hodgson: ‘75', 'description' => 'Passion. Betrayal. Harold Wilson. Character comedian Kieran Hodgson returns with the epic and surprising tale of how Britain joined Europe in the first place. On a deeply personal quest for understanding, Kieran perfects a series of obsolete impressions and discovers that the 70s were about more than just TISWAS, the colour brown and words ‘let’s go on strike again’.', 'start_time' => '2019/5/30  17:30:00', 'location' => 'Soho Theatre', 'rating' => 10));
        Event::create(array('id' => 15, 'category_id' => 2, 'name' => 'Nish Kumar: It\'s In Your Nature To Destroy Yourselves', 'description' => 'Double Edinburgh Comedy Award nominee Nish Kumar is touring his brand new show, It’s In Your Nature to Destroy Yourselves, around the UK. The title comes from a Terminator 2 quote. Expect jokes about politics, mankind’s capacity for self-destruction and whether or not this will lead to the end of days. Kumar is the host of the Mash Report. He\'s also been seen on Live at the Apollo, Taskmaster, Live From the BBC, QI, Have I Got News For You and Joel & Nish Vs The World.', 'start_time' => '2019/5/31  18:45:00', 'location' => 'Cheltenham Town Hall', 'rating' => 6));
        Event::create(array('id' => 16, 'category_id' => 2, 'name' => 'The Woman In Black', 'description' => 'Susan Hill’s acclaimed ghost story comes dramatically alive in Stephen Mallatratt’s ingenious stage adaptation. Starring Richard Hope as ‘Arthur Kipps’ and Mark Hawkins as ‘The Actor’. The Woman In Black is a gripping theatrical exploration of terror, \'a masterpiece\' (The Guardian) that\'s been thrilling audiences of all ages with its unique blend of suspense, drama and bold stagecraft. Now celebrating 27 terrifying years in the West End, Robin Herford’s gripping production is a brilliantly successful study in atmosphere, illusion and controlled horror.', 'start_time' => '2019/4/1  17:45:00', 'location' => 'Fortune Theatre', 'rating' => 8));
        Event::create(array('id' => 17, 'category_id' => 3, 'name' => 'London Lions v London City Royals', 'description' => 'Join London\'s only professional premier league basketball team for an all-round entertainment experience at one of their home games. Home fixtures are played at the Copper Box in Queen Elizabeth Olympic Park and their partnership with Sky Sports puts them at the forefront of basketball in this country. As well as watching the game, take in quality acts such as bands, singers and street dancers. You\'ll also have the opportunity to meet some players after every game, have a drink at their licensed bar, grab some dinner and feel like you are in America for the night!', 'start_time' => '2019/4/2  15:45:00', 'location' => 'Copper Box Arena', 'rating' => 8));
        Event::create(array('id' => 18, 'category_id' => 3, 'name' => 'Glasgow Clan V Guildford Flames', 'description' => 'Doors open at 6pm, face off 7pm. Please note all away fans must sit in the designated away section of the arena in block lower H.', 'start_time' => '2019/4/7  12:00:00', 'location' => 'Braehead Arena', 'rating' => 5));
        Event::create(array('id' => 19, 'category_id' => 3, 'name' => 'Stena Line Belfast Giants V Manchester Storm', 'description' => 'On Sunday 3 March, have the ULTIMATE family day out with W5 and the Stena Line Belfast Giants! Discover over 250 interactive exhibits at the award-winning Science & Discovery Centre and then watch NI\'s professional ice-hockey team hit the ice to take on Manchester Storm.', 'start_time' => '2019/4/9  13:00:00', 'location' => 'The SSE Arena', 'rating' => 5));
        Event::create(array('id' => 20, 'category_id' => 3, 'name' => 'Super Series Boxing', 'description' => 'Please Note: Strictly over 18s only. ID Required', 'start_time' => '2019/4/12  20:00:00', 'location' => 'O2 Forum Kentish Town', 'rating' => 6));
        Event::create(array('id' => 21, 'category_id' => 3, 'name' => 'For the Love of Darts', 'description' => 'Some of the world’s top professional darts players will compete at the BEC Arena when the Bowlers Manchester Darts Masters takes place on 08 March 2019. Arrows aces, including world number two Peter Wright and five-time World Champion Raymond van Barneveld, will put on a show for fans to enjoy the best night out in professional sport. ', 'start_time' => '2019/4/16  19:00:00', 'location' => 'Bowlers Exhibition Centre', 'rating' => 10));
        Event::create(array('id' => 22, 'category_id' => 3, 'name' => 'I.C.W: Fight Club', 'description' => 'Please Note: Over 18s only.', 'start_time' => '2019/5/5  21:00:00', 'location' => 'The Assembly', 'rating' => 10));
        Event::create(array('id' => 23, 'category_id' => 3, 'name' => 'Drift What Ya Brung Spectator Admission', 'description' => 'Drift What Ya Brung days at Santa Pod Raceway are days when you can come along and learn or practice drifting in safe and legal conditions on some of the Pods 30 acres of open tarmac. There are beginners, intermediate and advanced tracks open at the same time each DWYB day.', 'start_time' => '2019/4/22  11:00:00', 'location' => 'Santa Pod Raceway', 'rating' => 9));
        Event::create(array('id' => 24, 'category_id' => 4, 'name' => 'Cirque Du Soleil', 'description' => 'Cirque du Soleil returns to the Royal Albert Hall with Totem. Totem takes you on a stunning journey into the Evolution of Mankind – from our original amphibian state to our ultimate quest for flight. Alternating between primitive and modern myths, and peppered with aboriginal stories of creation, Totem explores the evolutionary process of species, our ongoing search for balance, and the curiosity that propels us ever further, faster, and higher… Featuring Cirque du Soleil’s mind-blowing signature acts, and returning to London after record-breaking previous seasons, Totem is an unforgettable spectacle for all ages.', 'start_time' => '2019/5/1  17:00:00', 'location' => 'Royal Albert Hall', 'rating' => 10));
        Event::create(array('id' => 25, 'category_id' => 4, 'name' => 'Ben and Holly\'s Little Kingdom', 'description' => '"Somewhere, hidden amongst the thorny brambles is a little kingdom where everyone is very very small..." From the makers of Peppa Pig comes this BAFTA Award-winning television animation for the first time ever live on stage! Holly is a young Fairy Princess, who is still learning how to fly and her magic doesn\'t always go quite according to plan. Her best friend, Ben the Elf, doesn\'t have wings and he doesn\'t do magic, but he runs very fast and flies on the back of Gaston the Ladybird. They live in the Little Kingdom, a tiny land where flowers and grass rise high above them and every day is an adventure.', 'start_time' => '2019/5/7  12:00:00', 'location' => 'Swansea Grand Theatre', 'rating' => 8));
        Event::create(array('id' => 26, 'category_id' => 4, 'name' => 'The Tiger Who Came to Tea', 'description' => 'The Tiger Who Came to Tea returns to the West End in 2018 for a very special summer season, celebrating its 10th anniversary on stage and 50 years of Britain’s best-loved picture book! The doorbell rings just as Sophie and her mummy are sitting down to tea. Who could it possibly be? What they certainly don\'t expect to see at the door is a big, stripy tiger! Join the tea-guzzling tiger in this delightful family show, packed with oodles of magic, sing-a-long songs and clumsy chaos! A stunning stage adaptation of the classic tale of teatime mayhem... expect to be surprised! Based on the book by Judith Kerr, this musical play is adapted and directed by David Wood OBE, who is undisputedly the country’s leading writer and director of plays and musicals for children. ', 'start_time' => '2019/4/3  13:00:00', 'location' => 'De La Warr Pavilion', 'rating' => 6));
        Event::create(array('id' => 27, 'category_id' => 4, 'name' => 'Mister Twister Magic Show', 'description' => 'Please Note: Under 14s must be accompanied by an adult over 18.', 'start_time' => '2019/4/10  10:00:00', 'location' => 'Playhouse, Whitley Bay', 'rating' => 5));
        Event::create(array('id' => 28, 'category_id' => 4, 'name' => 'Sooty\'s Magic Show', 'description' => 'Izzy Wizzy let\'s get Busy! - Introduce your children to the magic of Sooty! 5, 4, 3, 2, 1 Blastoff! Direct from their hit ITV series - it’s Sooty, Sweep, Soo and Richard in a Spectacular festive adventure! Sooty’s rocket is on the launch pad and he’s off to explore the final frontier... but with Sweep at the controls what could possibly go wrong? Everything! You’ll see the Amazing Space Station complete with Sooty’s Robot and Turbo Rocket. The Flight to Mars is presented in Magical 3D with a free pair of Space Goggles for everyone to take home.', 'start_time' => '2019/4/27  14:00:00', 'location' => 'King George\'s Hall', 'rating' => 6));
        Event::create(array('id' => 29, 'category_id' => 4, 'name' => 'Funbox Presents The Wild West Show', 'description' => 'Funbox is a show from Anya Scott-Rodgers, Gary Coupland and Kevin Macleod. Bringing a wealth of experience from their days as performers and writers of The Singing Kettle, they have created a sparkling show for kids of all ages – from nought to 90 – maintaining the balance of traditional singalong songs and brand new compositions, but with a distinctly Scottish flavour. Everyone’s favourite cheeky dog, Bonzo, is up to his usual mischief and there are loads of new friends too, including Fluffy and Flossie, the ever-helpful Funsters.', 'start_time' => '2019/4/15  15:00:00', 'location' => 'SEC Centre - Lomond Auditorium', 'rating' => 10));
        Event::create(array('id' => 30, 'category_id' => 4, 'name' => 'The Adventures of Pinocchio', 'description' => 'Immersion Theatre are thrilled to present a brand new, larger-than-life musical adaptation of the much-loved classic, Pinocchio! Based on Carlo Collodi’s fantastical children’s book, this magical story leaps off the page and onto the stage in a vibrant re-telling of Pinocchio’s extraordinary adventures.', 'start_time' => '2019/4/29  10:30:00', 'location' => 'Playhouse, Whitley Bay', 'rating' => 10));
        Event::create(array('id' => 31, 'category_id' => 5, 'name' => 'Enchantica', 'description' => 'Come on an adventure to the mythical realm of Enchantica. A three day camping festival full of mystery, magic and mythical creatures! Let your senses be heightened by the sounds of Live Music, allow it to resonate in your soul and gravitate you towards something beyond this world!', 'start_time' => '2019/4/5  16:00:00', 'location' => 'Cheltenham Racecourse', 'rating' => 7));
        Event::create(array('id' => 32, 'category_id' => 5, 'name' => 'BBC Countryfile Live 2019', 'description' => 'Countryfile Live is coming to Blenheim Palace and Castle Howard in August 2019! This huge and exciting event combines the tradition of the UK’s best county fairs with the quality editorial and presentation of one of the BBC’s flagship programmes. Enjoy exciting live arena shows, talks, hands-on activities, Adam Henson’s farm, animal displays, farming in action, Q&As with the Countryfile presenters, off-road experiences, shopping from more than 700 exhibitors including food, craft and luxury producers and even a great British pub garden.', 'start_time' => '2019/4/8  13:00:00', 'location' => 'Blenheim Palace', 'rating' => 9));
        Event::create(array('id' => 33, 'category_id' => 5, 'name' => 'Yarndale 2019', 'description' => 'Described as a “creative festival celebrating all things woolly and wonderful”, Yarndale plays host to an impressive selection of talented and passionate exhibitors. Stunning exhibitions, skill demonstrations and a full programme of textile workshops create a visual feast and make Yarndale a real must-visit for yarn lovers.', 'start_time' => '2019/4/12  11:00:00', 'location' => 'Skipton Auction Mart', 'rating' => 8));
        Event::create(array('id' => 34, 'category_id' => 5, 'name' => 'House of Common', 'description' => 'Madness are returning with the group\'s House of Common festival held at Clapham Common on the August bank holiday Monday. This one-day outdoor event features a line-up curated by Madness and culminating with a headline performance from the band themselves. Since forming in Camden, Madness have released 12 albums. House of Common is among the events planned this year to mark their four-decade-long career.', 'start_time' => '2019/4/26  18:00:00', 'location' => 'Clapham Common', 'rating' => 5));
        Event::create(array('id' => 35, 'category_id' => 6, 'name' => 'Bond In Motion', 'description' => 'The London Film Museum and EON Productions present the largest official collection of original James Bond vehicles. Come and see more than 100 original items on display from the James Bond films including cars, concept drawings, storyboards, scripts, model miniatures, boats and motorbikes!', 'start_time' => '2019/4/17  15:30:00', 'location' => 'Film Museum', 'rating' => 8));
        Event::create(array('id' => 36, 'category_id' => 6, 'name' => 'Good Grief, Charlie Brown!', 'description' => 'Good Grief! is a celebration of Peanuts, the world’s most influential comic strip and its cultural legacy. The exhibition has been developed in association with the Charles M. Schulz Museum and Research Center, Santa Rosa, California, U.S.A and features over 100 comic strips and artefacts from the Museum’s holdings. The exhibition uncovers the social, political and philosophical complexities told through the four-panel comic strip, which have inspired scores of artists in their own work. As a generation of artists who grew up during the ‘golden age’ of Peanuts come to prominence today, its presence in the ideas and ambitions of contemporary mediums, from film and fashion to street art and sculpture, seems more powerful and meaningful than ever before.', 'start_time' => '2019/4/19  10:00:00', 'location' => 'Embankment Galleries at Somerset House', 'rating' => 8));
        Event::create(array('id' => 37, 'category_id' => 6, 'name' => 'The Sun', 'description' => 'Spectacular interactive experiences, unique artefacts and stunning imagery shed fresh light on humanity\'s relationship with our closest star in the Science Museum\'s latest exhibition. From golden solar religious artefacts from the Nordic Bronze Age (dating back to 1400 BC), to details of upcoming NASA and ESA solar missions, The Sun: Living With Our Star tells the story of humankind’s dependence on, and ever changing understanding of, our star. Visitors to our latest blockbuster exhibition can bask in sunlight on our indoor beach, virtually try on a range of historic sunglasses in a digital mirror and see the Sun rise in different seasons and locations around the world on a huge illuminated wall display.', 'start_time' => '2019/4/19  12:00:00', 'location' => 'Science Museum', 'rating' => 8));
        Event::create(array('id' => 38, 'category_id' => 6, 'name' => 'Space Descent VR', 'description' => 'Tim Peake is your guide for an out-of-this-world virtual reality mission that puts you in the pilot\'s seat of a Soyuz capsule. As the European Space Agency\'s first British astronaut, Tim Peake spent six incredible months aboard the International Space Station. Now, let Tim be your guide on an out-of-this-world virtual reality mission that puts you in the pilot\'s seat of a Soyuz capsule—just like the one that brought him home. Using the latest state-of-the-art VR technology, you’ll get a 360° look inside a Soyuz capsule and experience the thrill of being an astronaut as you retrace Tim\'s 400km journey back to Earth from the ISS.', 'start_time' => '2019/4/23  09:00:00', 'location' => 'Science Museum', 'rating' => 7));
        Event::create(array('id' => 39, 'category_id' => 6, 'name' => 'MANDELA - The Official Exhibition', 'description' => 'Nelson Mandela was all of these things and more. Nelson Mandela: The Official Exhibition is the major new global touring exhibition that takes visitors on a personal journey through the life of the world’s most iconic freedom fighter and political leader. An immersive and interactive experience covering over 750 square meters, the exhibition featurespreviously unseen film, photos and the display of over 150 historical artefacts and personal effects on loan from the Mandela family, museums and archives worldwide. ', 'start_time' => '2019/4/24  13:00:00', 'location' => '26 Leake Street', 'rating' => 7));
        Event::create(array('id' => 40, 'category_id' => 6, 'name' => 'The Scottish Wedding Show', 'description' => 'Take the first steps to your dream wedding at The Scottish Wedding Show. We offer all the inspiration and expertise you need to plan your perfect day, with the widest range of exhibitors in Scotland and a host of exclusive features. For over a decade, The Scottish Wedding Show has been the No.1 destination for brides and grooms in the midst of wedding planning.  With up to 300 of the UK\'s leading wedding suppliers all under one roof, The Scottish Wedding Show is the ultimate bridal event, establishing itself as the one-stop-shop for the most savvy of brides across the country.', 'start_time' => '2019/4/26  14:00:00', 'location' => 'SEC Centre', 'rating' => 7));
        Event::create(array('id' => 41, 'category_id' => 6, 'name' => 'Leeds Tattoo Expo 2019', 'description' => 'The 6th annual Leeds Tattoo Expo will be held on 6th and 7th of July at First Direct Arena Leeds, Arena Way Leeds LS28BY. LITE will see around 180 top artists working under one roof to showcase some of the best in tattooing both locally and internationally. It is also home to a carefully selected market of boutique traders and a host of exciting entertainment across the weekend, along with the ever popular competitions for tattoo artists, held on Saturday and Sunday evenings. Plus the Second  Leeds Beard Competition.', 'start_time' => '2019/4/28  13:00:00', 'location' => 'First Direct Arena', 'rating' => 9));
        Event::create(array('id' => 42, 'category_id' => 6, 'name' => 'Tate Modern', 'description' => 'This is the first major exhibition of Pierre Bonnard’s work in the UK since the much-loved show at Tate 20 years ago. It will allow new generations to discover Bonnard’s unconventional use of colour, while surprising those who think they already know him.', 'start_time' => '2019/5/1  11:00:00', 'location' => 'Tate Shop', 'rating' => 6));
        Event::create(array('id' => 43, 'category_id' => 7, 'name' => 'At Eternity\'s Gate', 'description' => 'During a self-imposed exile in Arles and Auvers-Sur-Oise, France, Dutch painter Vincent van Gogh develops his unique, colorful style of painting. While grappling with religion, mental illness and a tumultuous friendship with French artist Paul Gauguin, van Gogh begins to focus on his relationship with eternity rather than the pain his art causes him in the present.', 'start_time' => '2019/4/02  18:00:00', 'location' => 'Cinamon Riga', 'rating' => 6));
        Event::create(array('id' => 44, 'category_id' => 7, 'name' => 'A Dog\'s Way Home', 'description' => '"A Dog’s Way Home" chronicles the heartwarming adventure of Bella, a dog who embarks on an epic 400-mile journey home after she is separated from her beloved human.', 'start_time' => '2019/4/8  20:00:00', 'location' => 'Splendid Palace', 'rating' => 10));
        Event::create(array('id' => 45, 'category_id' => 7, 'name' => 'Ralph Breaks the Internet', 'description' => 'Six years after the events of "Wreck-It Ralph," Ralph and Vanellope, now friends, discover a wi-fi router in their arcade, leading them into a new adventure.', 'start_time' => '2019/4/12  15:30:00', 'location' => 'Kino Bize', 'rating' => 10));
        Event::create(array('id' => 46, 'category_id' => 7, 'name' => 'Jacob, Mimmi and the Talking Dogs', 'description' => 'Jacob lives in the city and dreams of becoming an architect like his busy dad. He spends a lot of time drawing buildings and daydreaming while his father is at work. One day dad needs to go away on business for longer than usual and Jacob has to spend the whole week with his bossy cousin Mimmi and her ex-pirate father Eagle in Riga\'s historical suburb called Maskachka. As soon as Jacob arrives it turns out that the local park is about to be transformed into new skyscrapers by a greedy businessman. Jacob and Mimmi decide to stop the development. It turns out that they can only do it with the help of a pack of local dogs that... can talk! ', 'start_time' => '2019/4/15  17:00:00', 'location' => 'Kino Citadele', 'rating' => 9));
        Event::create(array('id' => 47, 'category_id' => 7, 'name' => 'Glass', 'description' => 'Security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities.', 'start_time' => '2019/4/18  18:30:00', 'location' => 'Multikino', 'rating' => 10));
        Event::create(array('id' => 48, 'category_id' => 7, 'name' => 'New Year\'s Eve Taxi', 'description' => 'New Year\'s Eve. Taxi driver Andrejs (Lauris Reiniks) has almost finished his shift, when suddenly a forgotten present makes him recall the curious collection of that night’s passengers - a rowdy couple, a tired Santa, noisy mummers, a worried groom, and even a pregnant woman about to have her baby. Andrejs will play a role in each passenger’s story, but will he get to experience his own New Year\'s miracle?', 'start_time' => '2019/4/20  21:00:00', 'location' => 'Kino Soprus', 'rating' => 8));
        Event::create(array('id' => 49, 'category_id' => 7, 'name' => 'Loro', 'description' => 'Paolo Sorrentino skewers Italian politics in this satirical, profane, and imaginative fictionalization of controversial Italian tycoon and politician Silvio Berlusconi and his inner circle.', 'start_time' => '2019/4/29  19:00:00', 'location' => 'ABC Cinema', 'rating' => 6));
        Event::create(array('id' => 50, 'category_id' => 7, 'name' => 'The Mule', 'description' => 'Earl Stone, a man in his 80s is broke, alone, and facing foreclosure of his business when he is offered a job that simply requires him to drive. Easy enough, but, unbeknownst to Earl, he\'s just signed on as a drug courier for a Mexican cartel. He does well – so well, in fact, that his cargo increases exponentially, and Earl is assigned a handler. But he isn\'t the only one keeping tabs on Earl; the mysterious new drug mule has also hit the radar of hard-charging DEA agent Colin Bates.', 'start_time' => '2019/5/10  17:00:00', 'location' => 'Cineworld Cinema', 'rating' => 6));
    }
}
